--RECIPE_CATEGORY TABLE INSERT
INSERT INTO RECIPE_CATEGORY(RECIPE_CATEGORY_NO,RECIPE_CATEGORY_NAME) VALUES(RECIPE_CATEGORY_NO_SEQ.NEXTVAL, '레시피국가');
INSERT INTO RECIPE_CATEGORY(RECIPE_CATEGORY_NO,RECIPE_CATEGORY_NAME) VALUES(RECIPE_CATEGORY_NO_SEQ.NEXTVAL, '레시피분류');
INSERT INTO RECIPE_CATEGORY(RECIPE_CATEGORY_NO,RECIPE_CATEGORY_NAME) VALUES(RECIPE_CATEGORY_NO_SEQ.NEXTVAL, '난이도');
------------------------------------------------------------------------------------
--RECIPE_DETAIL TABLE INSERT
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('동남아시아', 1);        --레시피국가
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('서양', 1);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('이탈리아', 1);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('일본', 1);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('중국', 1);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('퓨전', 1);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('한식', 1);

INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('국', 2);                --레시피분류
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('그라탕/리조또', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('나물/생채/샐러드', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('도시락/간식', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('떡/한과', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('만두/면류', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('밑반찬/김치', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('밥', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('볶음', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('부침', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('빵/과자', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('샌드위치/햄버거', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('양념장', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('양식', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('음료', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('조림', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('찌개/전골/스튜', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('찜', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('튀김/커틀릿', 2);
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('피자', 2);
                         
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('보통', 3);    			--레시피난이도
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('어려움', 3); 
INSERT INTO RECIPE_DETAIL(RECIPE_DETAIL_NAME,RECIPE_CATEGORY_NO) VALUES('초보환영', 3); 
------------------------------------------------------------------------------------
--POSTS TABLE INSERT
INSERT INTO POSTS(POST_NO,POST_TYPE_NO,USER_NO,POST_TITLE,POST_CONTENTS,POST_VIEW_COUNTS,POST_DATE) VALUES(POST_NO_SEQ.NEXTVAL, 1, 1, '콩국수가 싫다면 잣국수','시원한 여름국수요리!', 0, SYSDATE); 
INSERT INTO POSTS(POST_NO,POST_TYPE_NO,USER_NO,POST_TITLE,POST_CONTENTS,POST_VIEW_COUNTS,POST_DATE) VALUES(POST_NO_SEQ.NEXTVAL, 1, 2, '에어프라이어 마늘빵','SNS 핫한 트위터 겉바속촉 마늘빵 레시피 ', 0, SYSDATE); 
INSERT INTO POSTS(POST_NO,POST_TYPE_NO,USER_NO,POST_TITLE,POST_CONTENTS,POST_VIEW_COUNTS,POST_DATE) VALUES(POST_NO_SEQ.NEXTVAL, 1, 2, '순두부찌개 황금 레시피','SNS 핫한 트위터 겉바속촉 마늘빵 레시피 ', 0, SYSDATE); 


-------------------------------------------------------------------------------------
--RECIPES TABLE INSERT
INSERT INTO RECIPES(RECIPES_NO,RECIPES_NANE,POST_NO,RECIPES_CALORIE,RECIPES_COOKING_TIME,RECIPES_NATION,RECIPES_TYPE,RECIPES_LEVEL) VALUES(RECIPES_NO_SEQ.NEXTVAL,'잣국수',3, 513, 20, '한식', '만두/면류', '초보환영');
INSERT INTO RECIPES(RECIPES_NO,RECIPES_NANE,POST_NO,RECIPES_CALORIE,RECIPES_COOKING_TIME,RECIPES_NATION,RECIPES_TYPE,RECIPES_LEVEL) VALUES(RECIPES_NO_SEQ.NEXTVAL,'마늘빵',4, 276, 15, '서양', '빵/과자', '초보환영');
INSERT INTO RECIPES(RECIPES_NO,RECIPES_NANE,POST_NO,RECIPES_CALORIE,RECIPES_COOKING_TIME,RECIPES_NATION,RECIPES_TYPE,RECIPES_LEVEL) VALUES(RECIPES_NO_SEQ.NEXTVAL,'순두부찌개',5, 253, 30, '한식', '찌개/전골/스튜', '보통');

-------------------------------------------------------------------------------------
--INGREDIENTS TABLE INSERT
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,2,'잣',1,'150g');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,2,'닭 육수',2,'2+1/2종이컵');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,2,'소면',3,'1인분');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,2,'오이',4,'1/3개');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,2,'소금',5,'약간');

INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,3,'식빵',1,'2장');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,3,'마요네즈',2,'3숟갈');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,3,'설탕',3,'2숟갈');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,3,'다진마늘',4,'1숟갈');
INSERT INTO INGREDIENTS(INGREDIENT_NO,RECIPES_NO,INGREDIENT_NAME,INGREDIENT_SEQ,INGREDIENT_CACTY) VALUES(INGREDIENTS_NO_SEQ.NEXTVAL,3,'소금',5,'1꼬집');

-------------------------------------------------------------------------------------
--IMAGES TABLE INSERT
INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/c78ab39d260bfa1b8d49d4e612a918f31.png',3,3721); 
INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/72d6a27278d2eb32b960ceafd49ea2741.png',3,3395); 
INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/85cce2bddd66d150dc77adaf7e877ab41.png',3,2683); 
INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/7603c22d0bb956f0bfbe3d74df6a66161.png',3,2573); 

INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/a3c3003d1e1b8b9c5ba1047146de1d8f1.jpg',4,1542); 
INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/392b401c9c13aac2ae3609b67ba72ed31.jpg',4,2571); 
INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/f527619b4905735ab8215944771c0e081.jpg',4,1643); 
INSERT INTO IMAGES(IMAGE_URL,POST_NO,IMAGE_SIZE) VALUES ('https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/584b1fb73b02df4471f5a2f10e388b251.jpg',4,1924); 

-------------------------------------------------------------------------------------
--PROCESS TABLE INSERT
INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,2,'https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/c78ab39d260bfa1b8d49d4e612a918f31.png',1,'오이는 채 썬다.',NULL);
INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,2,'https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/72d6a27278d2eb32b960ceafd49ea2741.png',2,'믹서에 잣, 닭 육수, 소금을 넣고 곱게 간 후 체에 내린다.','잣 국물은 냉장고에 차게 보관해 주세요.');
INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,2,'https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/85cce2bddd66d150dc77adaf7e877ab41.png',3,'끓는 물에 소금을 넣고 소면을 넣어 삶는다.','찬물을 조금씩 넣어가며 삶으면 면이 더 쫄긴해져요');
INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,2,'https://recipe1.ezmember.co.kr/cache/recipe/2021/07/15/c78ab39d260bfa1b8d49d4e612a918f31.png',4,'그릇에 삶은 소면을 담고 잣 국물을 넉넉히 부은 후 채 썬 오이를 올려 완성한다.',NULL);

INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,3,'https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/a3c3003d1e1b8b9c5ba1047146de1d8f1.jpg',1,'그릇에 마요네즈, 설탕, 소금, 다진마늘을 넣고 골고루 섞어주세요.','설탕, 소금, 마늘, 마요네즈 순서로 계량하면 숟갈 한개로 끝나요 :) 설탕은 다 녹이는게 아니라 재료가 서로 골고루 섞일정도만');
INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,3,'https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/392b401c9c13aac2ae3609b67ba72ed31.jpg',2,'소스를 2등분하여 빵에 골고루 펴발라주세요.','소스가 도톰하게 발려야 겉은 바삭하고 속은 쫀득해요. 식빵도 좋고 바게트빵도 좋아요');
INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,3,'https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/f527619b4905735ab8215944771c0e081.jpg',3,'에어프라이어에 넣고 180℃에서 8분간 구워주세요.','위가 살짝 노릇할정도만 구워야 속이 쫀득합니다.');
INSERT INTO PROCESS(PROCESS_NO,RECIPES_NO,IMAGE_URL,PROCESS_SEQ,PROCESS_DESC,PROCESS_TIP) VALUES(PROCESS_NO_SEQ.NEXTVAL,3,'https://recipe1.ezmember.co.kr/cache/recipe/2019/12/25/584b1fb73b02df4471f5a2f10e388b251.jpg',4,'막 구워진 상태에서 먹어야 가장 맛이 좋습니다.',NULL);

------------------------------------------------------------------------------------- 

