--원재 연습장....

select * from users;

update USERS set USER_PROFILE_IMG='test.jpg' where USER_NO=4;
insert into USERS(USER_NO, USER_ID, USER_PWD, USER_NICNAME, USER_GENDER, USER_STATUS) values(3,'Jeon',1111,'전원재',0,10);
insert into USERS(USER_NO, USER_ID, USER_PWD, USER_NICNAME, USER_GENDER, USER_STATUS) values(4,'TestUser',1111,'테스트용',0,0);

update USERS set USER_STATUS=0 where USER_NO=4;
update USERS set USER_PWD='2222', USER_NICNAME='테스트', USER_GENDER=1 where USER_NO=4;

select * from posts;
select * from POSTS where USER_NO=4;
SELECT POST_NO, POST_TYPE_NO, POST_TITLE, POST_CONTENTS, POST_VIEW_COUNTS, POST_DATE, RECIPES_NO, RECIPES_NAME, RECIPES_CALORIE, RECIPES_COOKING_TIME, RECIPES_NATION, RECIPES_TYPE, RECIPES_LEVEL FROM POSTS INNER JOIN RECIPES USING(POST_NO) WHERE USER_NO=2;
INSERT INTO POSTS(POST_NO, POST_TYPE_NO, USER_NO, POST_TITLE, POST_CONTENTS, POST_VIEW_COUNTS, POST_DATE) VALUES(POST_NO_SEQ.NEXTVAL, 1, 4, '테스트','테스트하자', 0, SYSDATE);

select * from comments;
select * from comments where USER_NO=4;

INSERT INTO COMMENTS(COMMENT_NO, USER_NO, POST_NO, COMMENT_CONTENTS) 
VALUES(COMMENT_NO_SEQ.NEXTVAL, 4, 16, '테스트 하기 힘드네....');

select * from BOOKMARKS;
select * from BOOKMARKS where USER_NO=?;
insert into BOOKMARKS(USER_NO, POST_NO) values(4,16);
delete from BOOKMARKS where USER_NO=4 and POST_NO=16;

SELECT POST_NO, POST_TYPE_NO, POST_TITLE, POST_CONTENTS, POST_VIEW_COUNTS, POST_DATE, RECIPES_NO, RECIPES_NAME, RECIPES_CALORIE, RECIPES_COOKING_TIME, RECIPES_NATION, RECIPES_TYPE, RECIPES_LEVEL FROM POSTS INNER JOIN RECIPES USING(POST_NO) WHERE USER_NO=1;
SELECT * FROM POSTS INNER JOIN RECIPES USING(POST_NO) WHERE USER_NO=1;
SELECT * FROM (SELECT A.*,ROWNUM RNUM FROM POSTS INNER JOIN RECIPES USING(POST_NO) A) WHERE USER_NO=1 And RNUM BETWEEN 1 AND 5 ORDER BY POST_DATE DESC;
SELECT *, ROWNUM RNUM FROM POSTS INNER JOIN RECIPES USING(POST_NO);
SELECT * FROM (SELECT A.*,ROWNUM RNUM  FROM VIEW_RECIPES A WHERE USER_NO=2) WHERE RNUM BETWEEN 1 AND 5 ORDER BY POST_DATE DESC;

SELECT * FROM (SELECT A.*, ROWNUM RNUM FROM USERS A) WHERE RNUM BETWEEN 1 AND 5 ORDER BY USER_ENROLL_DATE DESC;

SELECT * FROM POSTS where USER_NO=2;
SELECT COUNT(*) FROM POSTS where USER_NO=2;
CREATE OR REPLACE VIEW VIEW_RECIPES AS SELECT * FROM POSTS NATURAL JOIN RECIPES;

SELECT COUNT(*) FROM COMMENTS;
SELECT * FROM COMMENTS;
SELECT * FROM (select A.*, ROWNUM RNUM from COMMENTS A where USER_NO=?) WHERE RNUM BETWEEN ? AND ? ORDER BY COMMENT_DATE DESC;

SELECT COUNT(*) FROM BOOKMARKS;
SELECT * FROM BOOKMARKS;
SELECT * FROM BOOKMARKS where user_no=3;
insert into BOOKMARKS(USER_NO, POST_NO) values(3,16);

SELECT COUNT(*) FROM POSTS where USER_NO=2 and POST_TYPE_NO=1;
SELECT * FROM POSTS where USER_NO=12 and POST_TYPE_NO in (3,4,5);
SELECT * FROM (SELECT A.*,ROWNUM RNUM  FROM POSTS A WHERE USER_NO=12 and POST_TYPE_NO in (3,4,5) ) WHERE RNUM BETWEEN 1 AND 5 ORDER BY POST_DATE DESC;
commit


